import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AEO GEO ",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <Script id="ai-overview-tracking" strategy="afterInteractive">
          {`
            (function(){
              try {
                // 1. Get the URL from Performance API (retains text fragment)
                var n = performance.getEntriesByType('navigation')[0];
                var u = n ? n.name : document.URL;
                
                // 2. Check for the text fragment
                if(u.includes(':~:text=')){
                  console.log('🎯 AI Overview Detected!');
                  
                  var r=0, s=function(){
                    // 3. Build the event payload
                    var p={
                      page_location: u,
                      page_path: new URL(u).pathname + new URL(u).hash
                    };
                    
                    // 4. Send to GA4 (supports both gtag and dataLayer)
                    if(typeof gtag!=='undefined'){
                      gtag('event','ai_overview_click', p);
                      console.log('✅ Event sent via gtag');
                    }
                    else if(window.dataLayer){
                      dataLayer.push({'event':'ai_overview_click', ...p});
                      console.log('✅ Event sent via dataLayer');
                    }
                    else if(r++<50){
                      setTimeout(s,200);
                    }
                  };
                  s();
                }
              } catch(e){ console.error(e); }
            })();
          `}
        </Script>

        {children}
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
